prometheus:
  service:
    type: NodePort


grafana:
  service:
    type: NodePort


alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-k8s-admin'
      routes: []
    receivers:
    - name: 'email-k8s-admin'
      email_configs:
      - to: kiran@lwplabs.com
        from: kiran@lwplabs.com
        smarthost: ####
        auth_username: ######
        auth_password: ######
  service:
    type: NodePort
