apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.21"

managedNodeGroups:
  - name: eks-node-group
    instanceType: t2.medium
    desiredCapacity: 1
